//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eatApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favori_Tablo
    {
        public string favoriId { get; set; }
        public string favoriYemekId { get; set; }
        public string favoriUyeId { get; set; }
    
        public virtual uye_Tablosu uye_Tablosu { get; set; }
        public virtual Yemekler Yemekler { get; set; }
    }
}
