//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eatApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malzeme_Tablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Malzeme_Tablosu()
        {
            this.Yemek_Tablosu = new HashSet<Yemek_Tablosu>();
        }
    
        public string malzeme_Id { get; set; }
        public string malzemeAdi { get; set; }
        public string malzeme_Kategori_Id { get; set; }
    
        public virtual Kategori_Tablosu Kategori_Tablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yemek_Tablosu> Yemek_Tablosu { get; set; }
    }
}
