//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eatApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malzeme_kategori
    {
        public string MalzemeKategoriId { get; set; }
        public string Malzeme_id { get; set; }
        public string Kategori_malzeme_id { get; set; }
    
        public virtual Kategori_malzeme Kategori_malzeme { get; set; }
        public virtual Malzemeler Malzemeler { get; set; }
    }
}
