//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eatApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YemekAppEntities : DbContext
    {
        public YemekAppEntities()
            : base("name=YemekAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<favori_Tablo> favori_Tablo { get; set; }
        public virtual DbSet<Kategori_malzeme> Kategori_malzeme { get; set; }
        public virtual DbSet<Kategori_yemek> Kategori_yemek { get; set; }
        public virtual DbSet<Malzeme_kategori> Malzeme_kategori { get; set; }
        public virtual DbSet<Malzemeler> Malzemeler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<takipci_Tablosu> takipci_Tablosu { get; set; }
        public virtual DbSet<uye_Tablosu> uye_Tablosu { get; set; }
        public virtual DbSet<Yemek_kategori> Yemek_kategori { get; set; }
        public virtual DbSet<Yemek_malzeme> Yemek_malzeme { get; set; }
        public virtual DbSet<Yemekler> Yemekler { get; set; }
    }
}
