//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eatApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eatAppEntities : DbContext
    {
        public eatAppEntities()
            : base("name=eatAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Begenilenler_Tablosu> Begenilenler_Tablosu { get; set; }
        public virtual DbSet<Kategori_Tablosu> Kategori_Tablosu { get; set; }
        public virtual DbSet<Malzeme_Tablosu> Malzeme_Tablosu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uye_Tablosu> Uye_Tablosu { get; set; }
        public virtual DbSet<Yemek_Tablosu> Yemek_Tablosu { get; set; }
    }
}
