//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eatApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YemekAppEntities2 : DbContext
    {
        public YemekAppEntities2()
            : base("name=YemekAppEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Birim> Birim { get; set; }
        public virtual DbSet<Birim_miktar> Birim_miktar { get; set; }
        public virtual DbSet<Kategori_malzeme> Kategori_malzeme { get; set; }
        public virtual DbSet<Kategori_yemek> Kategori_yemek { get; set; }
        public virtual DbSet<Malzemeler> Malzemeler { get; set; }
        public virtual DbSet<Miktar> Miktar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Yemek_malzeme> Yemek_malzeme { get; set; }
        public virtual DbSet<Yemekler> Yemekler { get; set; }
    }
}
