//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eatApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uye_Tablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uye_Tablosu()
        {
            this.Begenilenler_Tablosu = new HashSet<Begenilenler_Tablosu>();
            this.Yemek_Tablosu = new HashSet<Yemek_Tablosu>();
        }
    
        public string uye_Id { get; set; }
        public string uye_Adı_Soyado { get; set; }
        public string uye_E_Mail { get; set; }
        public string uye_Sifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Begenilenler_Tablosu> Begenilenler_Tablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yemek_Tablosu> Yemek_Tablosu { get; set; }
    }
}
