//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eatApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yemekler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yemekler()
        {
            this.favori_Tablo = new HashSet<favori_Tablo>();
            this.Yemek_kategori = new HashSet<Yemek_kategori>();
            this.Yemek_malzeme = new HashSet<Yemek_malzeme>();
        }
    
        public string yemekId { get; set; }
        public string YemekUyeId { get; set; }
        public string YemekAdi { get; set; }
        public string Tarif { get; set; }
        public string yemekFoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favori_Tablo> favori_Tablo { get; set; }
        public virtual uye_Tablosu uye_Tablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yemek_kategori> Yemek_kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yemek_malzeme> Yemek_malzeme { get; set; }
    }
}
