//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eatApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yemek_Tablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yemek_Tablosu()
        {
            this.Begenilenler_Tablosu = new HashSet<Begenilenler_Tablosu>();
        }
    
        public string yeme_Id { get; set; }
        public string yemek_Adi { get; set; }
        public string yemek_Malezeme_Id { get; set; }
        public string yemek_Kategori_Id { get; set; }
        public string yemek_Yapan_Id { get; set; }
        public string yemek_Tarif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Begenilenler_Tablosu> Begenilenler_Tablosu { get; set; }
        public virtual Kategori_Tablosu Kategori_Tablosu { get; set; }
        public virtual Malzeme_Tablosu Malzeme_Tablosu { get; set; }
        public virtual Uye_Tablosu Uye_Tablosu { get; set; }
    }
}
